# Generated by Django 3.1.7 on 2021-02-21 03:57

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_score',
            field=models.FloatField(blank=True, null=True, validators=[classroom.models.validate_negative]),
        ),
    ]
