# Generated by Django 3.1.7 on 2021-02-22 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210222_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=uuid.UUID('3b323411-310f-486f-8fba-6a67292b7cf4'), editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
