# Generated by Django 3.1.7 on 2021-02-22 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210222_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=uuid.UUID('088f33b0-4ddc-46af-85aa-b6c1d7cd3c16'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
