# Generated by Django 3.1.7 on 2021-02-22 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20210222_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=uuid.UUID('9d7a2a93-4b36-434e-81ee-16ecbd50ec4d'), editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
